// src/frontend/pages/login.vue
<template>
  <div class="h-full bg-base-200 flex justify-center">
    <div class="grid content-center pb-96">
      <div class="card bg-base-100 w-96 drop-shadow">
        <div class="card-body">
          <h2 class="card-title pb-4">ログイン</h2>
          <input
            v-model="user.email"
            type="text"
            placeholder="メールアドレス"
            class="input input-bordered w-full max-w-xs focus:outline-none focus:ring-4 focus:border-transparent focus:ring-daisy-primary"
          />
          <input
            v-model="user.password"
            type="password"
            placeholder="パスワード"
            class="input input-bordered w-full max-w-xs focus:outline-none focus:ring-4 focus:border-transparent focus:ring-daisy-primary"
          />
          <div class="card-actions justify-end pt-4">
            <button class="btn btn-primary text-base-100 drop-shadow" @click="login(user)">ログイン</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
definePageMeta({
  layout: 'before-login'
})

const user = reactive({
  email: '',
  password: ''
})

const login = (user) => {
  console.log(user)
}
</script>

// src/frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { SidebarService } from 'src/app/components/sidebar/sidebar.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: []
})
export class LoginComponent {
  constructor(
    private sidebarService: SidebarService
  ) {}

  ngOnInit(): void {
    this.sidebarService.hide();
  }

  ngOnDestroy(): void {
    this.sidebarService.show();
  }
}

<div class="bg-base-200 absolute inset-0 flex items-center justify-center">
  <div class="card bg-base-100 drop-shadow-lg w-96 sm:w-80">
    <div class="card-body">
      <h2 class="card-title pb-4">ログイン</h2>
      <input
        type="text"
        placeholder="メールアドレス"
        class="input input-bordered w-full max-w-xs focus:outline-none focus:ring-4 focus:border-transparent focus:ring-daisy-primary"
      />
      <input
        type="password"
        placeholder="パスワード"
        class="input input-bordered w-full max-w-xs focus:outline-none focus:ring-4 focus:border-transparent focus:ring-daisy-primary"
      />
      <div class="flex justify-start">
        <div class="pt-2 text-stone-500">パスワードを忘れた場合</div>
      </div>
      <div class="card-actions justify-end pt-4">
        <button
        class="btn btn-primary text-base-100 drop-shadow"
        >
          ログイン
        </button>
      </div>
      <div class="flex justify-end">
        <div class="pt-4 text-stone-500">ユーザ登録</div>
      </div>
    </div>
  </div>
</div>
